version: "3.9"
services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      - jenkins
    # network_alias: docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
      - "3000:3000"
      - "5000:5000"

networks:
  jenkins:

volumes:
  jenkins-docker-certs:
  jenkins-data:
